version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file: "./backend/.env"

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/certbot/conf/:/etc/letsencrypt/:rw
      - ./frontend/certbot/www/:/var/www/certbot/:rw
    env_file: "./frontend/.env"
    environment:
      - ENVIRONMENT=production   # ou "development" localmente

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./frontend/certbot/conf/:/etc/letsencrypt/:rw
      - ./frontend/certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
