version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8443:8443"
    volumes:
      - ./backend/app:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    env_file: "./backend/.env"

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: "./frontend/.env"
