version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file: "./backend/.env"

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "80:80"
    depends_on:
      - nginx
    env_file: "./frontend/.env"

  nginx:
    image: nginx:latest
    container_name: gym_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot:latest
    container_name: gym_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
