version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file: ".env"

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "3000:80"
    env_file: ".env"
