version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file: "./backend/.env"

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "80:80"
    env_file: "./frontend/.env"
