version: "3.8"
services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8443:8443"
    volumes:
      - ./backend/app:/app
      - ./data:/app/data
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    env_file: "./backend/.env"
    depends_on:
      - redis
    networks:
      - app_net

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: "./frontend/.env"
    networks:
      - app_net

  redis:
    image: redis:6
    container_name: gym_redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  celery_worker:
    build: ./backend
    container_name: gym_celery_worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    env_file: "./backend/.env"
    networks:
      - app_net

  celery_beat:
    build: ./backend
    container_name: gym_celery_beat
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
    env_file: "./backend/.env"
    networks:
      - app_net

networks:
  app_net:
    external: true