"""Adiciona colunas de pontuação para desafios

Revision ID: 7927cc4dbf80
Revises: e4ba0238d698
Create Date: 2025-02-13 00:42:44.820933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7927cc4dbf80'
down_revision: Union[str, None] = 'e4ba0238d698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_participants', sa.Column('challenge_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_participants', 'challenge_points')
    # ### end Alembic commands ###
